### ISSUE TITLE
Wrong PURLS in PCO (https)

### ISSUE THREAD

**Issue by matentzn** [PopulationAndCommunityOntology/pco#100]
https://purl.obolibrary.org/obo/PCO_0000040
https://purl.obolibrary.org/obo/PCO_0000041
https://purl.obolibrary.org/obo/PCO_0000042
https://purl.obolibrary.org/obo/PCO_0000043
https://purl.obolibrary.org/obo/PCO_0000044
https://purl.obolibrary.org/obo/PCO_0000045
https://purl.obolibrary.org/obo/PCO_0000046

An example of a correct IRI is (no https!):
http://purl.obolibrary.org/obo/ENVO_01000549

Context:
https://github.com/orgs/OBOFoundry/projects/5

**Comment by cmungall** [comment]
I think this is a dupe of #85 - I believe these were all fixed @ramonawalls  - maybe just need a new release?

**Comment by ramonawalls** [comment]
Yes. They have been fixed in #85
