### ISSUE TITLE
NewTerm: population migration and/or species migration

### ISSUE THREAD

**Issue by ramonawalls** [PopulationAndCommunityOntology/pco#12]
<a href="https://github.com/GoogleCodeExporter"><img src="https://avatars.githubusercontent.com/u/9614759?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [GoogleCodeExporter](https://github.com/GoogleCodeExporter)**
_Thursday Jun 11, 2015 at 23:48 GMT_
_Originally opened as https://github.com/rlwalls2008/pco/issues/17_

---

```
Please provide the following information:

Primary label for the proposed term: population migration and/or species 
migration

Definition: TBD

Definition source: ontology alignment workshop at NCEAS 3/2015

Name of submitter: R Walls

ORCID of submitter (if known):  orcid.org/0000-0001-8815-0078 

Any other information: Need to work with ENVO to talk about environmental 
processes that have as part or result from population migration.

```

Original issue reported on code.google.com by `rlwalls2...@gmail.com` on 4 Mar 2015 at 8:10

**Comment by ramonawalls** [comment]
<a href="https://github.com/GoogleCodeExporter"><img src="https://avatars.githubusercontent.com/u/9614759?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [GoogleCodeExporter](https://github.com/GoogleCodeExporter)**
_Thursday Jun 11, 2015 at 23:48 GMT_

---

Original comment by `rlwalls2...@gmail.com` on 16 Mar 2015 at 5:59
- Changed title: **NewTerm: population migration and/or species migration**
- Changed state: **Accepted**

**Comment by pbuttigieg** [comment]
Re-invigorating this and crosslinking to
https://github.com/EnvironmentOntology/envo/issues/470

PCO will provide the (collection of) organism(s) and ENVO the environments and space through which they move.

**Comment by ramonawalls** [comment]
These should go in ECOCORE.

**Comment by pbuttigieg** [comment]
PCO is best for these classes, but we'll create them in ENVO to save overhead and delays until OBO figures out a smoother way to sync edit files
