### ISSUE TITLE
NTR: microbial community

### ISSUE THREAD

**Issue by ramonawalls** [PopulationAndCommunityOntology/pco#22]
Subclass of ecological community

**Comment by ramonawalls** [comment]
Need to define microorganism (syn: microbe or "microbial organism"), probably in CARO. See https://en.wikipedia.org/wiki/Microorganism:
"A microorganism... is a microscopic living organism, which may be single celled or multicellular... Microorganisms are very diverse and include all the bacteria and archaea and almost all the protozoa. They also include some fungi, algae, and certain animals, such as rotifers. Many macroscopic animals and plants have microscopic juvenile stages. Some microbiologists also classify viruses (and viroids) as microorganisms..."

Could define microscopic in PATO (e.g., a size so small that ot cannot be detected without the aid of a microscope of other devise), and use that to define microorganism in PATO. Then it will be straightforward to add microbial community to PCO.

**Comment by pbuttigieg** [comment]
> Could define microscopic in PATO (e.g., a size so small that ot cannot be detected without the aid of a microscope of other devise), and use that to define microorganism in PATO. Then it will be straightforward to add microbial community to PCO.

microscopic as a quality makes sense, but I wouldn't have microorganism in PATO. As a building block for a microbial population / community (which would have subclasses added by inference), I think it's more natural to have it in PCO.

> Need to define microorganism (syn: microbe or "microbial organism"), probably in CARO. See https://en.wikipedia.org/wiki/Microorganism:

As above, seems more natural to in PCO to me, rather than an anatomy ontology, or is CARO used for such things too?

**Comment by ramonawalls** [comment]
I suggested CARO, because it has the parent term organism, virus or viroid. See obophenotype/caro#12. We'll see what @dosumis, @cmungall, and @mellybelly think. If it doesn't fit there, I will add it to PCO, but defining organism types would be a new area for PCO.

**Comment by pbuttigieg** [comment]
> I suggested CARO, because it has the parent term organism, virus or viroid. See obophenotype/caro#12. 

Thanks! It sounds like these sorts of organisms groupings (by size, lifestyle, etc) are creeping into other domains. I would thus hesitate to distribute them even more in onto-space. Such groupings are hugely useful, however, and are frequently used for systematics. Would it be absurd to build a small ontology for these kinds of groupings? Other domain ontologies can then surrender those classes and import if needed.

**Comment by ramonawalls** [comment]
This was fixed with pull#47
