### ISSUE TITLE
update axioms of household

### ISSUE THREAD

**Issue by ramonawalls** [PopulationAndCommunityOntology/pco#27]
Changed parent from 'material entity' to 'Homo sapiens' or 'collection of humans'.

**Comment by ramonawalls** [comment]
@zhengj2007 Please let me know if this change will work for you. I'm trying to make it more specific. 

At some point, we still need to add an axiom for living and sharing meals in the same residence.

**Comment by zhengj2007** [comment]
It works for me. Thanks!

**Comment by ramonawalls** [comment]
Will also request a new ENVO term for human dwelling (subclass of building and parent class of human house).
EnvironmentOntology/envo#264

**Comment by mark-jensen** [comment]
I notice that `household` is currently outside the BFO hierarchy. According to the axiom, shouldn't it appear under `material entity`?

**Comment by ramonawalls** [comment]
Once the reasoner is run, it is classified as a material entity.

**Comment by ramonawalls** [comment]
At least it should be :)

**Comment by mark-jensen** [comment]
What is this magical-sounding thing you call a reasoner?

**Comment by ramonawalls** [comment]
:) I'll send you some more information offline.

**Comment by ramonawalls** [comment]
I have imported the ENVO term for human dwelling, but we still need a way to specify that the people who are part of the household live and share meals in the same human dwelling.

**Comment by ramonawalls** [comment]
I was able to define this using the new relation occupies.

'organismal entity'
and ('has member' only 'Homo sapiens') and ('has member' min 1 'Homo sapiens')
and occupies some (site and 'located in' some 'human dwelling')
