### ISSUE TITLE
file format for pco.owl

### ISSUE THREAD

**Issue by ramonawalls** [PopulationAndCommunityOntology/pco#28]
@dosumis I notice pco.owl is now saved as OWL Functional Syntax. Sorry but I can't remember if we discussed doing this. If there is a good reason to leave it that way, I can learn to read it, but normally I would probably choose ttl. One nice thing I notices is that all the classes are listed in order in OFS. Challenge is finding the axioms that relate to a class.

**Comment by zhengj2007** [comment]
I think that is the format David prefer to use. He said it is easy to find out the difference between versions. Chris M. also recommended use this format since Github showed changes between versions including many unexpected stuffs when uses RDF/XML format. I am going to learn this format too.

**Comment by ramonawalls** [comment]
Okay. We will stick with OFS.
