### ISSUE TITLE
NTR: "plant community"

### ISSUE THREAD

**Issue by pbuttigieg** [PopulationAndCommunityOntology/pco#29]
Greetings!

Would it be possible to create a subclass of ecological community labelled "plant community" and defined as:
"An ecological community composed of members of the kingdom Plantae"

This is quite general, but useful. It can also be used with more complex communities as follows:
"rainforest community" has_part "plant community"

This relates to work on ecoregions and the like over at the prototype [Biogeographic Area Ontology](https://github.com/BiogeographicAreaOntology/)

**Comment by ramonawalls** [comment]
Sure. We can add that. I need to fix my NCBI import file anyway, so I can add Plantae then.

**Comment by ramonawalls** [comment]
In terms of the equivalancy axioms, I think this should say has member min 2 NCBI:Plantae, has member only NCBI:Plantae. Is this what you intended, @pbuttigieg? It is fairly restrictive, but I think consistent with many plant data sets.

**Comment by pbuttigieg** [comment]
> In terms of the equivalancy axioms, I think this should say has member min 2 NCBI:Plantae, has member only NCBI:Plantae.

Yes, sounds right if you mean min 2 populations of organisms from Plantae. The restriction is intended and probably quite useful. Many thanks!

**Comment by ramonawalls** [comment]
I was being a bit lazy before in using the term Plantae, which doesn't actually correspond to a clade.

We can define a plant kingdom based on one of the following:

Viridiplantae - green plants, includes green algae and land plants
Streptophyta - land plants plus charophytes (I don't recommend this one)
Embriophyta - land plants

I think the last one is what most people think of as a plant community, so I will make a class for that. To be clear, I will use "land plant community" as the primary label. Then we can always add a broader class for all green plants if it is needed.

**Comment by ramonawalls** [comment]
Added class http://purl.obolibrary.org/obo/pco.owl/PCO_0000204, with definition:

'ecological community'
 and ('has member' only Embryophyta)
