### ISSUE TITLE
Release OWL file should be an RDF dialect

### ISSUE THREAD

**Issue by cmungall** [PopulationAndCommunityOntology/pco#43]
http://purl.obolibrary.org/obo/pco.owl resolves to manchester.

This is fine by our current guidelines: 

http://obofoundry.org/principles/fp-002-format.html

However, I think it's good sensible practice to never use a format that can't be parsed outside the OWLAPI. 

See https://github.com/monarch-initiative/dipper/issues/401

In general I also recommend a more standard ROBOT-esque release file

**Comment by cmungall** [comment]
turns out you are turtle, oops, ignore

**Comment by alanruttenberg** [comment]
Concur on RDf/XML as that is the normative syntax according to the OWL specification.

Re robotesque, I don't know how one would accomplish that without actually running robot, which I don't think we should insist on. Instead document what minimal requirements for a release should be. Perhaps robot can be used to check those as part of the qc pipeline.

**Comment by cmungall** [comment]
Good suggestions.
