### ISSUE TITLE
admin issue: biosharing.org

### ISSUE THREAD

**Issue by jhammock** [PopulationAndCommunityOntology/pco#45]
I don't remember what connection might have gotten me listed as a contact, but this data standards aggregator just alerted me that their record for the PCO is "unclaimed". Would someone like to claim it?

https://biosharing.org/bsg-s002830

**Comment by pbuttigieg** [comment]
I think it was sent out to the PCO mailing list.

@Ramona : would you claim it?

**Comment by ramonawalls** [comment]
Done some time ago.
