### ISSUE TITLE
Clarify def for population process

### ISSUE THREAD

**Issue by pbuttigieg** [PopulationAndCommunityOntology/pco#53]
The class [`population process` ](http://purl.obolibrary.org/obo/PCO_0000005) has the textual def:
```
A process that has as primary participant a population.
```

For ecoCore purposes, we'd need to specific about reference to an `ecological population` or `single-species population`, could this be clarified in the def and perhaps with an axiom like: 
```
'has participant some 'ecological population'
```
?

**Comment by ramonawalls** [comment]
The has participant axiom already exists. To help clarify, I moved most of the comment into the definition.
