### ISSUE TITLE
Add 'biological family' as subtype of 'family'

### ISSUE THREAD

**Issue by mbrush** [PopulationAndCommunityOntology/pco#57]
I am working with the [ClinGen DMWG](http://datamodel.clinicalgenome.org/interpretation/) to build a model supporting clinical variant interpretations, and we are looking to re-use as possible from existing ontologies. We need the concept of a biological/genealogical family for the purpose of describing pedigree analyses.  It seems that the PCO community has previously considered adding such a term in #3, and I think that this proposal is largely in line with what we need.  
  
The definition below is adapted from the proposed definition in these prior discussions - but we have removed the phrase "and whose members form a socially interacting group" - as we do not want to require that members of a biological family necessarily interact socially.

tagging @ramonawalls here as i don't have repo permissions to assign.

-----------

## Preferred term label
biological family

## Synonyms
genealogical family

## Textual definition
"A collection of organisms of the same species whose members are all either genealogically related to each other or have mated with each other"

## Suggested parent term

PCO:0000020 'family'

**Comment by mbrush** [comment]
Hi @ramonawalls. Any thoughts on this request, or clarifications I can make! Thanks!

**Comment by ramonawalls** [comment]
@mbrush  Sorry I didn't notice this when it came it! I see no problems with the term you suggest, other than it will be challenging to define it logically. I can add it to PCO with a text definition as a start. I will try to do a release before next Monday so you can have the term.

**Comment by ramonawalls** [comment]
New term created, http://purl.obolibrary.org/obo/PCO_0000032.

Still have to do release.

**Comment by ramonawalls** [comment]
Release was just pushed, this term is now available for use.
