### ISSUE TITLE
Permission for PCO pull request

### ISSUE THREAD

**Issue by kaiiam** [PopulationAndCommunityOntology/pco#61]
Hello @ramonawalls.  As part of the work of my masters thesis supervised by @pbuttigieg I have prepared a considerable amount of material for a potential Pull request for PCO, and I am wondering if I could get thoughts on such material. A sample of some of the types of classes I wish to propose are fit into the hierarchy as follows. Defined example classes are shown with an Asterisk*.

Please let me know if you feel this work will benefit PCO and you are ok with the design pattern I am opening up, as well as if I have your permission to submit such a pull request.   

```
material entity
  ecological community
    plankton community*
      phytoplankton community
        diatom-dominated community
  ...
  microbial community
    cyanobacteria-dominated microbial community*
    ...

process
  biological process
    multi-organism process 
      ecological community process*
        community establishment process*
        carrying capacity saturation by a community
        multiplicative community growth to carrying capacity saturation transition
          community bloom saturation
            algal bloom saturation*
       ...

  population process
    population decline
    population bloom*
    carrying capacity saturation to population decline transition
      population bloom collapse*
    ...
  
```

### plankton community
```
An ecological community which reside in a body of water and are unable to sustain directed movement to overcome displacement by physical forces such as currents.
```
``is a 'ecological community'``

``'located in' some 'water body'`` ENVO:[water body](http://purl.obolibrary.org/obo/ENVO_00000063)

``'has exact synonym' 'plankton'``

[dbxref](https://en.wikipedia.org/wiki/Plankton)

### cyanobacteria-dominated microbial community
```
A microbial community which is composed primarily of bacteria of the phylum Cyanobacteria.
```
``is a 'microbial community'``

``'composed primarily of' some Cyanobacteria`` NCBITaxon:[Cyanobacteria](http://purl.obolibrary.org/obo/NCBITaxon_1117)

``'causal agent in' some 'photoautotrophy'`` ECOCORE:[photoautotrophy](http://purl.obolibrary.org/obo/ECOCORE_00000013)

``'participates in' some 'photoautotrophic biomass formation'`` ENVO:[no purl yet]()

``'has part' some 'chlorophyll'`` CHEBI:[chlorophyll](http://purl.obolibrary.org/obo/CHEBI_28966)

``'has related synonym' 'blue-green algae'`` 

[dbxref](https://en.wikipedia.org/wiki/Cyanobacteria)

### ecological community process
```
A multi-organism process that has as primary participant an ecological community. 
```
``is a 'multi-organism process'``

``'occurs in' some ecosystem`` ENVO:[ecosystem](http://purl.obolibrary.org/obo/ENVO_01001110)

``'has participant' some 'ecological community'``

### community establishment process
```
A process during which at least two of the populations in a community are introduced into a new environment, or are subject to different environmental conditions, and in which individuals must undergo physiological or behavioral changes in order for populations within the community to realize their net potential reproduction rate within their new environment.
```
``is a 'ecological community process'``

``'has part' some 'community persistence process'``

``'has part' some 'population establishment process'``

[dbxref1](https://en.wikipedia.org/wiki/Population_growth) [dbxref2](https://en.wikipedia.org/wiki/Bacterial_growth) [dbxref3](ISBN-13: 978-0691123448)

### algal bloom saturation 
```
A community process during which at least two of the populations in a algal community undergoing a bloom, achieve a maximum growth rate and or size.   
```
``is a 'community bloom saturation'``

``'causally downstream of or within' some 'algal bloom process'``

### population bloom
```
A population process during which a population within an ecosystem undergo rapid growth, resulting in high abundances that occur only periodically and briefly in that ecosystem, relative to their concentrations through the majority of the planetary orbital period.
```
``is a 'population process'``

[dbxref1](https://en.wikipedia.org/wiki/Bloom), [dbxref2](https://doi.org/10.1007/s10750-012-1048-6)

### population bloom collapse
```
A population process during which the rapid growth of a population undergoing a population bloom ceases, and the population size decreases due to death, predation, transport or displacement.
```
``is a 'carrying capacity saturation to population decline transition'``

``'has part' some 'population decline'``

``ends some 'population bloom'``

``'causally downstream of or within' some 'population bloom'``

**Comment by ramonawalls** [comment]
@kaiiam I am very happy to have you issue this pull request for PCO. At first glance, I don't see any problems with the design patterns. I will need to review everything carefully once you issue the request.

My only question at this point is about the relation 'composed primarily of'. Is that from RO? I am not familiar with it.

**Comment by kaiiam** [comment]
@ramonawalls Thanks for the quick reply, and for the feedback. I'm glad to hear you like the design patterns I'm proposing. The relation  'composed primarily of' is from RO [purl here](http://purl.obolibrary.org/obo/RO_0002473)

 @pbuttigieg and I will submit the pull request this weekend, with contributions from both of us.

**Comment by kaiiam** [comment]
I still have all these terms floating around if you think they'd benefit PCO.
