### ISSUE TITLE
NTR: tidal mangrove shrubland community

### ISSUE THREAD

**Issue by pbuttigieg** [PopulationAndCommunityOntology/pco#66]
## Preferred term label

tidal mangrove shrubland community

## Synonyms
related: mangrove community
related: tidal shrubland community

## Textual definition

An ecological community which is composed primarily of  dwarf or short mangroves, often populations of Laguncularia racemosa, Avicennia germinans, Sarcocornia pacifica, or Batis maritima. 

## Suggested parent term

For now, just under ecological community:
http://purl.obolibrary.org/obo/PCO_0000002 

## Cross-axiomatisation

This can be linked to ENVO:`tidal mangrove shrubland` (http://purl.obolibrary.org/obo/ENVO_01001369) which is a semantic casting of CMECS unit 577. Right now, the ENVO class cross-links to NCBITax's classes for the species noted in the definition.  These should probably be ported over to PCO.

## Attribution

https://orcid.org/0000-0002-4366-3088
Please also link to this CMECS class as a dbxref:
https://cmecscatalog.org/cmecs/classification/unit/577.html

**Comment by ramonawalls** [comment]
Wow, I completely missed this. My apologies. Please go ahead and make a PR for this term and I will add it. Perhaps you have already moved on.

**Comment by ramonawalls** [comment]
Until I get a dbxref property, I am adding the link to CMECS as a comment.

**Comment by ramonawalls** [comment]
@pbuttigieg What the relationship between a tidal mangrove shrubland community and ENVO:tidal mangrove shrubland? Part of?

**Comment by ramonawalls** [comment]
I am going to hold off on adding this new class, because ENVO: tidal mangrove community references the old PCO term for community rather than ecological community. I will release the new version of PCO first, then fix the imports in ECOCORE and ENVO, then recreate this class.

**Comment by ramonawalls** [comment]
Nevermind that last comment (which is already deleted). It was just a new way that protege displays obsolete classes.
