### ISSUE TITLE
Appropriate place for describing population sample methods and measures?

### ISSUE THREAD

**Issue by richardostler** [PopulationAndCommunityOntology/pco#67]
I'm after some guidance on describing sampling methods for surveying and estimating earthworm populations, but am not sure if this is the right ontology and if it is where, in the ontology to suggest placing. The methods are fairly specific to earthworms, but my issues with population estimates are more general. 

I have three methods to describe:

1. formalin expulsion: pouring a diluted formalin solution on to the soil. This acts as an irritant and emerging earthworms are then collected from a defined area, identified and counted.
2. mustard expulsion: as above but using a solution of mustard powder.
3. excavation: a volume (usually a cube) of soil is dug up then manually sorted to identify and count worms in the volume.

In each case, the sampled population is used to estimate abundance / unit area e.g. endogeic worms/m<sup>2</sup>. Wet weight biomass is also estimated as g/m<sup>2</sup>.

The terms abundance and biomass don't seem to be defined in PCO, although I can see the ECOCORE imports [organic material](http://purl.obolibrary.org/obo/ENVO_01000155) from ENVO which has biomass as a synonym, however, I'm not convinced this is an appropriate definition for biomass in ecology which is the mass of living organisms in a given area. So, would this ecological biomass definition be a better fit for PCO, or perhaps ECOCORE, then ENVO?

**Comment by ramonawalls** [comment]
@richardostler I'm sorry I did not see this sooner. 

PCO does not currently cover any assays of the type you have defined. I would suggest putting those in either OBI (more general, https://github.com/obi-ontology/obi) or BCO (specific to biodiversity studies, https://github.com/BiodiversityOntologies/bco).   I can help with writing logical definitions for the terms if needed, regardless of which ontology you decide is better suited. 

Biomass and abundance could go in either PCO or EcoCore, but I think ECOCORE is a better home. Please file an issue there and tag me, if you don't mind.

**Comment by richardostler** [comment]
@ramonawalls no worries and thanks. I wasn't aware of BCO so will check it out. I'll add an issue to ECOCORE for biomass and abundance.
