### ISSUE TITLE
NTR: gender arrangements

### ISSUE THREAD

**Issue by diatomsRcool** [PopulationAndCommunityOntology/pco#69]
For new term requests, please provide the following information: 
See also https://github.com/EcologicalSemantics/ecocore/issues/36

## Preferred term label
diandrous
monandrous

## Textual definition

(I'm unsure of these definitions)

Protogynous species with both juvenile females and (primary) males, where a certain percentage of females changes into (terminal) males are termed diandric, also: possessing two different types of males, a large, brightly-coloured and aggressive terminal phase (TP) and a smaller, drab and relatively non-aggressive initial phase

Protogynous hermaphrodites with only juvenile females, where a certain percentage of females changes into (terminal) males are termed monandric.

## Suggested parent term

reproductive quality PATO:0001434

## Attribution

If you would like a nanoattribution, please indicate your ORCID id.
http://orcid.org/0000-0002-2908-3327

**Comment by ramonawalls** [comment]
I think it might be better to have these terms in PATO directly.

**Comment by ramonawalls** [comment]
Although I think these terms are out of scope for PCO, we need to figure out the PCO term in which they should inhere.  I'm not sure if any of the existing terms (below) are quite right. 

**population of organisms:** A collection of organisms, all of the same species, that live in the same place.

**species as a collection of organism:** A collection of organisms that has as parts every organism of given species and no organisms of any other species.

**single species collection of organism:** A material entity that has as parts two or more organisms, viruses, or viroids of the same species and no members of any other species.

**Population of organisms** probably works, but often people use these adjectives to describe **species as a collection of organism**, in which case it would be better to use their common parent, **single species collection of organism**.

**Comment by ramonawalls** [comment]
Make PR in PATO

**Comment by ramonawalls** [comment]
Fixed with PATO PR https://github.com/pato-ontology/pato/pull/350
