### ISSUE TITLE
Add microbiome as synonym of microbial community

### ISSUE THREAD

**Issue by cmungall** [PopulationAndCommunityOntology/pco#70]
Carried from https://github.com/obi-ontology/obi/issues/990

Prev ticket #22

Add microbiome as synonym of microbial community

I would argue for exact synonym: but there is an argument that microbiome can mean any arbitrary sample of microbes regardless of their structure or interactions. I think it's better to use the term more strictly

In fact I might argue for microbiome be the primary label

**Comment by ramonawalls** [comment]
I think of microbiome as a microbial community that lives in another organism, but I am not the expert on this. I'll try to get input from those that are.

Would also be good to add microbiota as a label.

**Comment by pbuttigieg** [comment]
> Add microbiome as synonym of microbial community

I'd be cautious here. A related synonym would be good as there's all sorts of fuzziness here.

> I would argue for exact synonym: but there is an argument that microbiome can mean any arbitrary sample of microbes regardless of their structure or interactions. I think it's better to use the term more strictly

Many understand a microbiome as "just" a collection of organisms, but others are more rigorous in their ecology and understand it as a biome determined by a microbial community. If you injected a mock community into someone's gut that was mostly made up of ocean microbes, very few would seriously call it a gut microbiome without a bunch of gymnastics.

@phismith and I had an exchange over this when a microbiome ontology was emerging. We got to the stage where ENVO would host microbiomes under or close to "biome", as the communities have adapted to and often define their hosting environment. PCO:microbial community would be used to axiomatise this.

> I think of microbiome as a microbial community that lives in another organism...

No, the ocean/soil/air microbiome are all counterexamples, and living in a place isn't sufficient (as explained above).

>Would also be good to add microbiota as a label.

That would likely be the exact synonym.

**Comment by ramonawalls** [comment]
As per EnvironmentOntology/envo#807 comment 514640565:

1. need to add microbiome as related synonym to microbial community
2. Discuss moving [microbiota](http://www.ontobee.org/ontology/OHMI?iri=http://purl.obolibrary.org/obo/OHMI_0000463) into PCO, perhaps as an exact synonym for microbial community. Will discuss this with @zhengj2007 and @yongqunh.

**Comment by ramonawalls** [comment]
This issue is subsumed under #73
