### ISSUE TITLE
Community

### ISSUE THREAD

**Issue by Mttbnchtt** [PopulationAndCommunityOntology/pco#72]
The definition of _community_ in PCO is "A collection of organisms of the same species whose members are all either genealogically related to each other or have mated with each other."

There are three issues:
1. This makes it wrong to have _ecological community_ as a subclass (as it is the case now), because "ecological community" is defined as a community having populations of _different_ species.
2. The current definition makes it impossible to talk about a _community of priests_ (no genealogical relations and no mating), although this is a legitimate expression.
3. In general, the current definition is not suited to talk about things like a community of vulnerable persons. 

I wonder whether PCO would be interested in changing the definition to take into account these issues.

@pbuttigieg may also be interested.

**Comment by yongqunh** [comment]
We also found the same issue in our OHMI (ontology of host-microbiome interactions). The 'microbial community' (http://purl.obolibrary.org/obo/PCO_1000004) definition: 
An ecological community which is composed of co-existing populations of microbial organisms that interact, directly or indirectly, such that they impact one another's ecological fitness.

The 'microbial community' appears to refer to different species. However, as introduced above, the 'community' is for the same species. This is confusing. 

In our microbiome research area, a 'microbiota' can be a lot of organisms from the same species, or from different species. We don't want to specify one or more species for 'microbiota'. In this case, it is hard to make 'microbiota' a synonym of 'microbial community'. 

@pbuttigieg may also be interested in this.

**Comment by pbuttigieg** [comment]
Yes, this needs revision.

Ecological community (of which microbial communities are a subclass) necessarily have more than one ecological population in them.

@yongqunh good point. Microbiota can be a broad synonym of microbial community, but should probably be a subclass of collection of organisms with an axiom like `'has part' min 1 'microbial population'` where microbial population is under ecological population.

**Comment by ramonawalls** [comment]
This is clearly a mistake and makes no sense. I will have to go back and look at the history to figure out how it arose so that it can be fixed.

**Comment by yongqunh** [comment]
Hi Ramona,

Will you attend the ICBO-2019?
Happy to chat with you there if you go.

Thanks,
Oliver

**Comment by ramonawalls** [comment]
I am around tomorrow and Tuesday. Looking forward to lots of in person conversations!

Enviado de Baja Arizona

**Comment by ramonawalls** [comment]
See #32.  I am going to get rid of community, and make ecological community a direct subclass of multi-species collection of organisms. 

@Mttbnchtt please advise if you need a term for community that does not fall within ecological community.

**Comment by ramonawalls** [comment]
I just talked with Pier and he explained the use case for the class `community` (e.g., for SDGIO and related work). I will add it back in. We might also want to make a class for `human community`.
