### ISSUE TITLE
Add new terms an hierarchy for microbiota

### ISSUE THREAD

**Issue by ramonawalls** [PopulationAndCommunityOntology/pco#73]
See also #70, EnvironmentOntology/envo#807, and OHMI-ontology/OHMI#2. 

Following an in person discussion with @zhengj2007 and @yongqunh, we decided to keep the current term for [microbial community](http://purl.obolibrary.org/obo/PCO_1000004), but to add some other microbioata classes for other use cases, in the hierarchy below:

- collection of organisms
-- collection of microbial organisms
--- multi-species collection of microbes
---- microbial community
--- single species collection of microbes
-- multi-species collection of organisms
--- ecological community
---- microbial community
--- multi-species collection of microbes
---- microbial community
-- single-species collection of organisms
--- population of organisms
---- microbial population

This is a complex hierarchy, so I will make a PR soon for people to review, and to make sure I got it right.

New terms:

`collection of microbial organisms`: A collection of organisms consisting of two or more microbes.
exact synonym: microbiota

`multi-species collection of microbes`: A multi-species collection of organisms that consists of two or more microbes from at least two species.

`single species collection of microbes`: A single-species collection of organisms that consists of two or more microbes of the same species and no members of any other species.

`microbial population`:  A population of organisms consisting of only microbes of the same species, that live in the same place.
broad synonym: microbiota

For reference, the existing term is:
`microbial community`: An ecological community which is composed of co-existing populations of microbes that interact, directly or indirectly, such that they impact one another's ecological fitness.
Add broad synonym: microbiota

**Comment by ramonawalls** [comment]
@zhengj2007 and @yongqunh I added these classes to pco-edit.owl. Do you want to check them before I do a release?

**Comment by zhengj2007** [comment]
@ramonawalls I trust you and would like you to go ahead and make the release.

**Comment by yongqunh** [comment]
@ramonawalls yes. please go ahead to release the terms. We will later then import these terms to OHMI. Thanks.

**Comment by ramonawalls** [comment]
Thanks @zhengj2007  and @yongqunh. I'll let you know when the new release is done.

**Comment by zhengj2007** [comment]
Thanks @ramonawalls

**Comment by ramonawalls** [comment]
The release is out. I made a typo in the version IRI, so it say 2020-02-13 instead of 2020-02-12, but I don't think that will affect anything important, so I am going to leave it, and tomorrow it will be the 13th!
