### ISSUE TITLE
NTR: microbe

### ISSUE THREAD

**Issue by ramonawalls** [PopulationAndCommunityOntology/pco#74]
This term is being moved to PCO from OHMI

## Preferred term label

microbe

## Synonyms

microbial organism

## Textual definition

An organism or virus or viroid that is too small to be viewed by the unaided eye.

## Logical definition

'organism or virus or viroid'
 and ('has quality' some 'invisible to unaided eye')

## Suggested parent term

organism or virus or viroid (will soon be replaced by "organism" from CORE)

## Attribution

@zhengj2007 and @yongqunh please supply your ORCIDs so I can include them.

**Comment by ramonawalls** [comment]
Will need to add new quality `invisible to the naked eye`, which should eventually go into PATO.
def: A physical object quality that is inhered in a material entity that is too small to be viewed by the unaided eye.

**Comment by ramonawalls** [comment]
Needed to define microbial collections of organisms, per issue #73.

**Comment by ramonawalls** [comment]
@pbuttigieg Please let us know if you want any changes to this one or #73. We should include you as a contributor as well.

**Comment by zhengj2007** [comment]
@ramonawalls my ORCID is 0000-0002-2999-0103. Thanks!

**Comment by ramonawalls** [comment]
@cmungall, in EnvironmentOntology/envo#781 you suggested including non-monophyletic groups in NCBITaxon. Would that be the appropriate home for this microbe class?

**Comment by cmungall** [comment]
Different namespace, but it could be built as part of the obo ncbitaxon releases, and released as an optional extension

but I think this should be reserved for things that can be logically defined using or/and/not with existing taxo... this one feels odd let's discuss later
