### ISSUE TITLE
Update definition of household

### ISSUE THREAD

**Issue by ramonawalls** [PopulationAndCommunityOntology/pco#75]
Now that household is a subclass, its text definition should be updated to say "An organismal entity that consists of one or more people who live in the same dwelling and also share at meals or living accommodation, and may consist of a single family or some other grouping of people."

It would be good to add an axiom about living in a dwelling. @cmungall, are there any appropriate RO relations for this, or should we request one?

See ufbmi/OMRSE#88

**Comment by cmungall** [comment]
one might be tempted to use has-habitat by the name, but this wouldn't be
quite right, but it could be a relation in the same family

**Comment by ramonawalls** [comment]
The challenge here is that it is difficult to 'lives in'. For now, I am going to use the general relation `ecologically related to`.
