### ISSUE TITLE
creation of a class for species range needed in the biorealm ontology

### ISSUE THREAD

**Issue by thearyung** [PopulationAndCommunityOntology/pco#76]
in our new biorealm ontology we would like to express the areas where a population of taxa live and interact with its ecosystem.
We propose the following:
label: population range

definition: an ecosystem which is delimited by the ranges of an ecological population

**Comment by ramonawalls** [comment]
Would this be a subclass of ENVO:ecosystem or a part of an ecosystem?

**Comment by pbuttigieg** [comment]
Sounds like a part of  min 1 ecosystem. In a "pure" sense, it's more like a spatial region / site; practically it wouldn't be distinguishable from an ecosystem.

 Is this really a PCO entity? Maybe ECOCORE is better @diatomsRcool ?

**Comment by ramonawalls** [comment]
@pbuttigieg This was moved here from ECOCORE. I think it fits in PCO because of its direct relationship to a population of organisms, but I could be out voted and move it back to ECOCORE. Either way, we should decide soon so @thearyung isn't left waiting.

**Comment by pbuttigieg** [comment]
> label: population range
> definition: an ecosystem which is delimited by the ranges of an ecological population

This above is circular.

Try:
"An ecosystem within which members of a given taxon can be found."

Also note the variants of range: https://en.wikipedia.org/wiki/Range_(biology)#Range

**Comment by pbuttigieg** [comment]
> This was moved here from ECOCORE. I think it fits in PCO because of its direct relationship to a population of organisms

I don't think so - it's broader than PCO's usual content and would result in mission creep. It's also one of those core ecological principles that ECOCORE was designed to host.

**Comment by ramonawalls** [comment]
Make PR in ecocore

**Comment by ramonawalls** [comment]
I added this to Ecocore as a subclass of `environmental zone` which is a site that is part of some ecosystem. I'll do a PR there as soon as I get access to the repo.
