### ISSUE TITLE
NTR: number of generations of multicellular organism

### ISSUE THREAD

**Issue by zhengj2007** [PopulationAndCommunityOntology/pco#77]
## Preferred term label
number of generations of multicellular organism

## Synonyms
number of generations

## Textual definition
A data item of the number of steps in the line of descent from a common ancestor.

## Suggested parent term
IAO_0000027 data item

## Definition source
EFO_0000507 generation, NCIT_C88214 generation

## Suggested Axiom
is about' only 'multicellular organism' (CARO_0000012)

## Attribution
https://orcid.org/0000-0002-2999-0103

The term originally submitted to OBI, tracker: https://github.com/obi-ontology/obi/issues/1094. OBI developers thought it fits PCO scope better. Please let me know if PCO does not like to take the term. Thanks!

**Comment by ramonawalls** [comment]
We can add this. I'll try to do a release within the next month.

**Comment by zhengj2007** [comment]
Thanks @ramonawalls

**Comment by zhengj2007** [comment]
Hi @ramonawalls, any update on this tracker? Thanks!

**Comment by ramonawalls** [comment]
Sorry I missed this @zhengj2007 . I will include it in the release I plan to do by end of next week.

**Comment by zhengj2007** [comment]
Thanks @ramonawalls

**Comment by zhengj2007** [comment]
Hi @ramonawalls, any progress on it? When will be the term available? Thanks!

**Comment by ramonawalls** [comment]
@zhengj2007 I would like to make this a subclass of  http://purl.obolibrary.org/obo/STATO_0000047 (count): "a count is a data item denoted by an integer and represented the number of instances or occurences of an entity". Count is a subclass of `measurement datum`. Does that work for OBI? I have several other count classes I am working on as well.

I am just a few days away from a release now. Sorry for the delay. Would it help to have a term IRI sooner? I could mint that now.

**Comment by ramonawalls** [comment]
http://purl.obolibrary.org/obo/PCO_0000054
