### ISSUE TITLE
Simplify axiom structure for ecological community

### ISSUE THREAD

**Issue by cmungall** [PopulationAndCommunityOntology/pco#83]
https://www.ebi.ac.uk/ols/ontologies/pco/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPCO_0000002

![image](https://user-images.githubusercontent.com/50745/81595310-1fac5380-9377-11ea-956c-8338a3d7171b.png)

Can we split this into two SubClassOf axioms? Logically equivalent. See https://github.com/ontodev/robot/issues/690

This is currently messing with our envo release, we end up with ecological community hanging out at the root, just as it does in OLS and OntoBee http://purl.obolibrary.org/obo/PCO_0000002

**Comment by cmungall** [comment]
Note: I think all that is needed here for robot reason to be run prior to release, using a DL reasoner

**Comment by ramonawalls** [comment]
I have changed this axiom, but it is still going to inherit the compound axiom from `collection of organisms`: 

equivalent to
(RO_0002351 only 'organism or virus or viroid')
 and (RO_0002351 min 2 'organism or virus or viroid')

Does that cause problems, @cmungall ? I don't think we can get rid of that one.

**Comment by ramonawalls** [comment]
Also, I don't understand why this is hanging out as a subclass of thing in OLS, since in http://purl.obolibrary.org/obo/pco.owl it is a subclass of `multi-species collection of organisms`, since I run the reasoner before release.
