### ISSUE TITLE
versioned purls do not resolve

### ISSUE THREAD

**Issue by cmungall** [PopulationAndCommunityOntology/pco#84]
```
$ curl -L -s http://purl.obolibrary.org/obo/pco.owl | grep versionIRI
        <owl:versionIRI rdf:resource="http://purl.obolibrary.org/obo/pco/releases/2020-02-13/pco.owl"/>
$ curl -L -s http://purl.obolibrary.org/obo/pco/releases/2020-02-13/pco.owl
404: Not Found

```

**Comment by ramonawalls** [comment]
This is an issue in the OBO Foundry YAML file, which I will fix for both releases after this release is done.

**Comment by ramonawalls** [comment]
I don't understand why these are not working. By my understanding, specifying

`- exact: /releases/2020-02-12/pco.owl
  replacement: https://raw.githubusercontent.com/PopulationAndCommunityOntology/pco/2020-02-12/pco.owl
`
Should result in the purl `http://purl.obolibrary.org/obo/pco/releases/2020-02-12/pco.owl` that resolves to `https://raw.githubusercontent.com/PopulationAndCommunityOntology/pco/2020-02-12/pco.owl`. 

If I paste `http://purl.obolibrary.org/obo/pco/releases/2020-02-12/pco.owl` into a browser it works. I must be misunderstanding what happens with the line `- exact: /releases/2020-02-12/pco.owl`.

@cmungall can you tell me what I am missing? P.S., I did re-read all the documentation at https://github.com/OBOFoundry/purl.obolibrary.org first.

**Comment by cmungall** [comment]
This works:

```bash
curl -L -s http://purl.obolibrary.org/obo/pco/releases/2020-02-12/pco.owl
```

The issue is that the 2020-02-12 PURL resolves to OWL that declares it has a 2020-02-13 PURL, and you have no registered entry here. Guess you were making a release around midnight...?

btw, one advantage of having `/releases/` in the PURL is that you can have a generic redirect, rather than registering the cross-product of all products of all releases. This is how we do it for ENVO:

https://github.com/OBOFoundry/purl.obolibrary.org/blob/049f288db1f8c9f4b0aa004a1318601cc5772652/config/envo.yml#L22-L23

**Comment by ramonawalls** [comment]
OMG, it is simple. I never even thought about a typo in the date. 

Yes, I plan to add prefix redirects too, but I wanted to make sure I understood properly.

Thank you, @cmungall !
