### ISSUE TITLE
PCO has an https class PURL for multi-species collection of microbes

### ISSUE THREAD

**Issue by cmungall** [PopulationAndCommunityOntology/pco#85]
See:

```
    <!-- https://purl.obolibrary.org/obo/PCO_0000044 -->

    <owl:Class rdf:about="https://purl.obolibrary.org/obo/PCO_0000044">
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/PCO_0000029"/>
        <rdfs:subClassOf rdf:resource="https://purl.obolibrary.org/obo/PCO_0000043"/>
        <obo:IAO_0000115 xml:lang="en">A multi-species collection of organisms that consists of two or more microbes from at least two species.</obo:IAO_0000115>
        <dc:creator xml:lang="en">https://orcid.org/0000-0001-8815-0078</dc:creator>
        <rdfs:label xml:lang="en">multi-species collection of microbes</rdfs:label>
    </owl:Class>
```

this actually causes massive problems

we're using this class in ENVO, cc @pbuttigieg 

I think the cleanest thing is just to fix the PURL, remove the s from https

Now formally PURLs should not go away. But obsoleting this one and then accidentally reinstating a new PURL with the same ID but different URL scheme could potentially be disastrous

we need standard ODK checks for this!!

**Comment by cmungall** [comment]
aactually we're not using this directly in envo, we use a subclass

**Comment by ramonawalls** [comment]
Hmm. I'll fix this one and check the other terms that were created at the same time. Probably I had protege configured incorrectly.

**Comment by ramonawalls** [comment]
Yes, this was a whole batch of terms added at the same time:

PCO_0000040 tidal mangrove shrubland community

PCO_0000041 invisible to unaided eye

PCO_0000042 microbe

PCO_0000043 collection of microbial organisms

PCO_0000044 multi-species collection of microbes

PCO_0000045 single species collection of microbes

PCO_0000046 microbial population


@zhengj2007 @yongqunh: This will impact your work, so please be aware that this change is coming. I will keep the terms the same, but give them new IRIs.
