### ISSUE TITLE
NTR: organism count

### ISSUE THREAD

**Issue by ramonawalls** [PopulationAndCommunityOntology/pco#86]
For new term requests, please provide the following information:

## Preferred term label

organism count

## Synonyms

organismal count

## Textual definition

A count that inheres in an organism or collection of organisms of the same taxon. 

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/pco]

## Attribution

https://orcid.org/0000-0001-8815-0078

NOTE:
Also make a subclass for organism count by taxon, in which all organisms counted are of the same taxon.

**Comment by kaiiam** [comment]
xref https://github.com/UA-SRC-data/srpdio/issues/3

**Comment by ramonawalls** [comment]
@kaiiam 

The problem with the proposed definition is that often the count is zero, which then can't inhere in an organism. We had this same challenge in the PPO, which we solved by defining `plant structure presense` as "A 'plant phenological trait' that is measured by the number of some 'plant structure' that are part of a 'whole plant'." 

I propose a similar definition for organism count (syn: organism amount): An amount that is measured by the number of organisms of the same taxon.

To define this more clearly, I think we should create a subclass of BCO:observing process that is organism counting process. In fact, I think this class should be in BCO, not PCO. I will move the ticket there.

**Comment by ramonawalls** [comment]
Looks like I can't transfer between orgs. Will close this one and open a new one in BCO.

**Comment by kaiiam** [comment]
xref https://github.com/BiodiversityOntologies/bco/issues/115
