### ISSUE TITLE
NTRs: Shannon and Simpson diversity

### ISSUE THREAD

**Issue by kaiiam** [PopulationAndCommunityOntology/pco#94]
For the UA-SRC project we'll need to represent some data which has to do with diversity metric calculated upon microbial 16S sequence data. Specifically, `Richness`, `Shannon`, `Simpson`, and `Inverse Simpson` diversity. 

We currently have the term [community species richness](http://purl.obolibrary.org/obo/PCO_0000010) suitable for `Richness` under the [quality of an ecological community](http://purl.obolibrary.org/obo/PCO_0000004) hierarchy. 

Perhaps we could add the following terms?

## community species shannon diversity index

Definition:

> A community species diversity metric that accounts for both the abundance and evenness of the species present quantified via the following formula: the negative sum of, the product of the proportion of species i relative to the total number of species (pi) multiplied by the natural logarithm of this proportion (ln pi).

**Parent class**

[community species diversity](http://purl.obolibrary.org/obo/PCO_0000019)

**References**

https://doi.org/10.1002%2Fj.1538-7305.1948.tb01338.x

http://www.tiem.utk.edu/~gross/bioed/bealsmodules/shannonDI.html

## community species simpson diversity index

Definition: 

> A community species diversity metric that is quantified via the following formula: the reciprocal of the sum of squared  proportion of species i relative to the total number of species (pi).

**Parent class**

[community species diversity](http://purl.obolibrary.org/obo/PCO_0000019)

**Reference**

http://www.tiem.utk.edu/~gross/bioed/bealsmodules/simpsonDI.html

## community species inverse simpson diversity index

Definition: 

> A community species diversity metric that is quantified via the following formula: the sum of squared  proportion of species i relative to the total number of species (pi).

Comment:

> The inverse simpson diversity index is the reciprocal of the (standard) simpson diversity index. 

**Parent class**

[community species diversity](http://purl.obolibrary.org/obo/PCO_0000019)

**References**

http://www.tiem.utk.edu/~gross/bioed/bealsmodules/simpsonDI.html

https://mothur.org/wiki/invsimpson/ 

@ramonawalls let me know what you think and please double check me on this. Do we want to try and add this to the July 2020 release?

**Comment by ramonawalls** [comment]
Thanks @kaiiam! I'll get this in the release today. I will use the wikipedia references, though, since I think they are more stable than the .edu ones.
