### ISSUE TITLE
NTR: alpha, beta, gamma diversity

### ISSUE THREAD

**Issue by cmungall** [PopulationAndCommunityOntology/pco#96]
http://bioportal.bioontology.org/search?utf8=%E2%9C%93&query=alpha+diversity&button=

this is already in OHMI (inheriting from PCO grouping) but it seems the concept should be independent of concept of host-microbiome interactions, applies to ecology as a whole

and should this be modeled as a property class or data property?

**Comment by ramonawalls** [comment]
We have several terms for already diversity which are modeled as subclasses of PATO:quality, inhering in an ecological community. I think alpha, beta, and gamma diversity could be subclasses of PCO_0000019, community species diversity.
